config/routes.rb
Rails.application.routes.draw do

  resources :missing_posts
  resources :donations do
    post 'donate', on: :collection
    member do
      get 'confirm_donate'
      get 'confirm_delete'
    end
  end


  resources :vacunas, only: [:new, :create, :edit, :edit2, :update, :destroy] do
    member do
      get 'confirm_delete'
      get 'confirm_delete2'
      get 'edit2'
      post 'edit2'
    end
  end

  get '/download_HistoriaClinica/:dog_id(.:format)', to: 'medical_stories#downloadHC', as: 'download_historia_clinica', defaults: { format: :pdf }
  get '/download_LibretaSanitaria/:dog_id(.:format)', to: 'health_records#downloadLS', as: 'download_libreta_sanitaria', defaults: { format: :pdf }

  resources :health_records do
  end
  
  resources :medical_stories do
  end

  resources :dogs do
    member do
      get 'confirm_delete'
    end
  end
  resources :registers, only: [:index, :new, :create]
  resources :admin_registers, only: [:index, :new, :create]
  get 'dashboard/home'
  root 'homepage#home'

  devise_for :users, skip: [:registrations], controllers: { sessions:'users/sessions'}

  # Rutas para editar usuario y otras funcionalidades proporcionadas por Devise
  resources :users, only: [:edit, :update] do
    member do
      get 'user_dogs', to: 'dogs#index_user_dogs', as: 'user_dogs'
    end
  end

  # Rutas personalizadas para el registro de usuario
  get "/registers", to: "registers#new", as: :new_user_registration
  post "/registers", to: "registers#create", as: :user_registration
  # Rutas para editar y actualizar la contraseña
  get "/registers/edit/:id", to: "registers#edit", as: :edit_user_registration
  patch "/registers/update/:id", to: "registers#update", as: :update_user_registration

  # Rutas de cuidadores y paseadores
  resources :caregivers do
    member do
      get 'confirm_delete'
    end
  end
  get '/u/caregivers', to: 'caregivers#index_user', as: :index_user_caregiver
  post 'u/caregivers/:id/request', to: 'caregivers#solicitar'
  get 'u/caregivers/:id/request', to: 'caregivers#solicitar', as: :solicitar_cuidador
  post 'u/caregivers/:id/report', to: 'caregivers#reportar'
  get 'u/caregivers/:id/report', to: 'caregivers#reportar', as: :reportar_cuidador

  resources :walkers do
    member do
      get 'confirm_delete'
    end
  end
  get '/u/walkers', to: 'walkers#index_user', as: :index_user_walker
  post 'u/walkers/:id/request', to: 'walkers#solicitar'
  get 'u/walkers/:id/request', to: 'walkers#solicitar', as: :solicitar_paseador
  post 'u/walkers/:id/report', to: 'walkers#reportar'
  get 'u/walkers/:id/report', to: 'walkers#reportar', as: :reportar_paseador

  resources :medical_story do
    member do
      get 'confirm_delete'
    end
  end

  resources :health_record do
    member do
      get 'confirm_delete'
    end
  end

  # Rutas turnos "Santi"

  resources :appointments do
    member do
      get 'confirm_delete'
    end
  end

  patch 'appointments/:id/confirm_user_edit', to: 'appointments#confirm_user_edit', as: 'confirm_user_edit'

  patch 'appointments/:id/confirm_admin_edit', to: 'appointments#confirm_admin_edit', as: 'confirm_admin_edit'

  patch 'confirmed/:id/remove_cancel', to: 'appointments#remove_cancel', as: 'remove_cancel'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/:id/confirm_cancel', to: 'appointments#confirm_cancel', as: :confirm_cancel_appointment
  get '/:id/edit', to: 'appointments#edit', as: :edit__appointment

  get '/requests', to: 'appointments#index_requests', as: :requests
  get '/requests/:id', to: 'appointments#show_request', as: :request

  get '/confirmed', to: 'appointments#index_confirmed', as: :confirmed
  get '/confirmed/:id', to: 'appointments#show_confirmed', as: :confirmed_show


  resources :adoptions do
    member do
      patch 'confirm'
      get 'confirm_delete'
    end
  end

  post 'adoption/:id/request', to: 'adoptions#solicitar'
  get 'adoption/:id/request', to: 'adoptions#solicitar', as: :solicitar

  resources :missing_posts do
    member do
      patch 'confirm'
      get 'confirm_delete'
    end
  end

  post 'missing_post/:id/request', to: 'missing_posts#solicitar'
  get 'missing_post/:id/request', to: 'missing_posts#solicitar', as: :mp_solicitar

end

app/views/shared/_header.html.erb
<div class="p-3 mb-3 bg-info-subtle text-emphasis-info"></div>
<td class = "border-gray-50"></td>

app/views/shared/_sidebar.html.erb
<div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
          <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel">
            <div class="offcanvas-header">
              <h5 class="offcanvas-title" id="sidebarMenuLabel">Menu</h5>
              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu" aria-label="Close"></button>
            </div>
            <nav class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 ">
              <ul class="nav flex-column" id="sidebarNav" data-bs-spy="scroll" data-bs-target="#sidebarNav">              
                <li class="nav-item">
                  <%= link_to dashboard_home_path, class:"nav-link d-flex align-items-center gap-2 text-dark" do %>
                      <i class="bi bi-house-fill"></i> Inicio
                  <% end %>
                </li>

                <% if current_user && current_user.admin? %>
                   <li class="nav-item">
                    <%= link_to requests_path, class:"nav-link d-flex align-items-center gap-2 text-dark" do %>
                        <i class="bi bi-calendar-plus"></i> Solicitud de turnos
                    <% end %>
                    <li class="nav-item">
                    <%= link_to confirmed_path, class:"nav-link d-flex align-items-center gap-2 text-dark" do %>
                        <i class="bi bi-calendar-check-fill"></i> Turnos confirmados
                    <% end %>
                    <li class="nav-item">
                    <%= link_to caregivers_path, class:"nav-link d-flex align-items-center gap-2 text-dark" do %>
                        <i class="bi bi-house-heart"></i></i> Cuidadores
                    <% end %>
                    <%= link_to walkers_path, class:"nav-link d-flex align-items-center gap-2 text-dark" do %>
                        <i class="bi bi-person-walking"></i> Paseadores
                    <% end %>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to appointments_path, class:"nav-link d-flex align-items-center gap-2 text-dark" do %>
                        <i class="bi bi-calendar"></i> Turnos
                    <% end %>
                    <%= link_to index_user_caregiver_path, class:"nav-link d-flex align-items-center gap-2 text-dark" do %>
                        <i class="bi bi-house-heart"></i></i> Cuidadores
                    <% end %>
                    <%= link_to index_user_walker_path, class:"nav-link d-flex align-items-center gap-2 text-dark" do %>
                        <i class="bi bi-person-walking"></i> Paseadores
                    <% end %>
                  </li>
                <% end %>
                
                <li class="nav-item">
                  <%= link_to adoptions_path, class:"nav-link d-flex align-items-center gap-2 text-dark" do %>
                        <i class="bi bi-search-heart"></i> Adopción
                    <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to missing_posts_path, class:"nav-link d-flex align-items-center gap-2 text-dark" do %>
                        <i class="bi bi-heartbreak-fill"></i> Perros perdidos
                  <% end %>
                </li>


                <li class="nav-item">
                  <%= link_to donations_path, class:"nav-link d-flex align-items-center gap-2 text-dark" do %>
                    <i class="bi bi-piggy-bank-fill"></i> Donaciones
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to dogs_path, class:"nav-link d-flex align-items-center gap-2 text-dark" do %>
                      <%= image_tag("dog-solid.svg", class: "example-icon") %> 
                      <% if current_user.admin?%>
                        Perros
                      <% else %>
                        Mis perros
                      <% end %>
                  <% end %>
                 </li>
                <% if current_user && current_user.admin? %>
                  <li class="nav-item">
                  <%= link_to registers_path, class:"nav-link d-flex align-items-center gap-2 text-dark" do %>
                      <i class="bi bi-people"></i> Clientes
                  <% end %>
                  </li>
                  <li class="nav-item">
                  <%= link_to admin_registers_path, class:"nav-link d-flex align-items-center gap-2 text-dark" do %>
                      <i class="bi bi-person-gear"></i> Administradores
                  <% end %>
                  </li>
              <% end %>
              </ul>
              <ul class="nav flex-column mt-auto">
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, class:"nav-link d-flex align-items-center gap-2 text-dark",'data-turbo-method': :delete do %>
                    <i class="bi bi-door-closed"></i> Cerrar sesión
                  <% end %>
                </li> 
              </ul>
            </nav>
          </div>
        </div>