config/routes.rb
Rails.application.routes.draw do

  resources :missing_posts
  resources :donations do
    post 'donate', on: :collection
    member do
      get 'confirm_donate'
      get 'confirm_delete'
    end
  end


  resources :vacunas, only: [:new, :create, :edit, :edit2, :update, :destroy] do
    member do
      get 'confirm_delete'
      get 'confirm_delete2'
      get 'edit2'
      post 'edit2'
    end
  end

  get '/download_HistoriaClinica/:dog_id(.:format)', to: 'medical_stories#downloadHC', as: 'download_historia_clinica', defaults: { format: :pdf }
  get '/download_LibretaSanitaria/:dog_id(.:format)', to: 'health_records#downloadLS', as: 'download_libreta_sanitaria', defaults: { format: :pdf }

  resources :health_records do
  end
  
  resources :medical_stories do
  end

  resources :dogs do
    member do
      get 'confirm_delete'
    end
  end
  resources :registers, only: [:index, :new, :create]
  resources :admin_registers, only: [:index, :new, :create]
  get 'dashboard/home'
  root 'homepage#home'

  devise_for :users, skip: [:registrations], controllers: { sessions:'users/sessions'}

  # Rutas para editar usuario y otras funcionalidades proporcionadas por Devise
  resources :users, only: [:edit, :update] do
    member do
      get 'user_dogs', to: 'dogs#index_user_dogs', as: 'user_dogs'
    end
  end

  # Rutas personalizadas para el registro de usuario
  get "/registers", to: "registers#new", as: :new_user_registration
  post "/registers", to: "registers#create", as: :user_registration
  # Rutas para editar y actualizar la contraseña
  get "/registers/edit/:id", to: "registers#edit", as: :edit_user_registration
  patch "/registers/update/:id", to: "registers#update", as: :update_user_registration

  # Rutas de cuidadores y paseadores
  resources :caregivers do
    member do
      get 'confirm_delete'
    end
  end
  get '/u/caregivers', to: 'caregivers#index_user', as: :index_user_caregiver
  post 'u/caregivers/:id/request', to: 'caregivers#solicitar'
  get 'u/caregivers/:id/request', to: 'caregivers#solicitar', as: :solicitar_cuidador
  post 'u/caregivers/:id/report', to: 'caregivers#reportar'
  get 'u/caregivers/:id/report', to: 'caregivers#reportar', as: :reportar_cuidador

  resources :walkers do
    member do
      get 'confirm_delete'
    end
  end
  get '/u/walkers', to: 'walkers#index_user', as: :index_user_walker
  post 'u/walkers/:id/request', to: 'walkers#solicitar'
  get 'u/walkers/:id/request', to: 'walkers#solicitar', as: :solicitar_paseador
  post 'u/walkers/:id/report', to: 'walkers#reportar'
  get 'u/walkers/:id/report', to: 'walkers#reportar', as: :reportar_paseador

  resources :medical_story do
    member do
      get 'confirm_delete'
    end
  end

  resources :health_record do
    member do
      get 'confirm_delete'
    end
  end

  # Rutas turnos "Santi"

  resources :appointments do
    member do
      get 'confirm_delete'
    end
  end

  patch 'appointments/:id/confirm_user_edit', to: 'appointments#confirm_user_edit', as: 'confirm_user_edit'

  patch 'appointments/:id/confirm_admin_edit', to: 'appointments#confirm_admin_edit', as: 'confirm_admin_edit'

  patch 'confirmed/:id/remove_cancel', to: 'appointments#remove_cancel', as: 'remove_cancel'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/:id/confirm_cancel', to: 'appointments#confirm_cancel', as: :confirm_cancel_appointment
  get '/:id/edit', to: 'appointments#edit', as: :edit__appointment

  get '/requests', to: 'appointments#index_requests', as: :requests
  get '/requests/:id', to: 'appointments#show_request', as: :request

  get '/confirmed', to: 'appointments#index_confirmed', as: :confirmed
  get '/confirmed/:id', to: 'appointments#show_confirmed', as: :confirmed_show


  resources :adoptions do
    member do
      patch 'confirm'
      get 'confirm_delete'
    end
  end

  post 'adoption/:id/request', to: 'adoptions#solicitar'
  get 'adoption/:id/request', to: 'adoptions#solicitar', as: :solicitar

  resources :missing_posts do
    member do
      patch 'confirm'
      get 'confirm_delete'
    end
  end

  post 'missing_post/:id/request', to: 'missing_posts#solicitar'
  get 'missing_post/:id/request', to: 'missing_posts#solicitar', as: :mp_solicitar

end

app/models/caregiver.rb
class Caregiver < ApplicationRecord
  validates :phoneNum, presence: true, format: { with: /\A\d+\z/, message: "El télefono solo puede números, revise el campo e inténtelo nuevamente. "}
  has_many :users, dependent: :nullify

  has_many :reported_caregiver_associations, class_name: 'ReportedCaregiver', foreign_key: 'caregiver_id'
  has_many :reporting_users, through: :reported_caregiver_associations, dependent: :nullify
end

app/controllers/caregivers_controller.rb
class CaregiversController < ApplicationController
  before_action :authenticate_user!, except: [:index_user, :solicitar]
  before_action :set_caregiver, only: %i[ show edit update destroy]
  before_action :authenticate_admin, only: [:index, :show, :new, :edit, :create, :update, :destroy, :confirm_delete]
  before_action :only_user, only: [:reportar]

  # GET /caregivers or /caregivers.json
  def index
    @caregivers = Caregiver.all
  end

  def index_user
    @caregivers = Caregiver.all
  end

  # GET /caregivers/1 or /caregivers/1.json
  def show
  end

  # GET /caregivers/new
  def new
    @caregiver = Caregiver.new
  end

  # GET /caregivers/1/edit
  def edit
  end

  # POST /caregivers or /caregivers.json
  def create
    @caregiver = Caregiver.new(caregiver_params)

    respond_to do |format|
      if @caregiver.save
        format.html { redirect_to caregiver_url(@caregiver), notice: "Cuidador creado exitosamente." }
        format.json { render :show, status: :created, location: @caregiver }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @caregiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caregivers/1 or /caregivers/1.json
  def update
    respond_to do |format|
      if @caregiver.update(caregiver_params)
        format.html { redirect_to caregiver_url(@caregiver), notice: "Cuidador editado exitosamente." }
        format.json { render :show, status: :ok, location: @caregiver }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @caregiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caregivers/1 or /caregivers/1.json
  def destroy
    @caregiver.destroy
    respond_to do |format|
      format.html { redirect_to caregivers_url, notice: "Cuidador eliminado exitosamente." }
      format.json { head :no_content }
    end
  end

  def confirm_delete
    @caregiver = Caregiver.find(params[:id])
  end

  def reportar
    @caregiver = Caregiver.find(params[:id])
    user = User.find(current_user.id)
    @name = user.name
    @lastname = user.surname
    @phone = user.phoneNum
    @mail = user.email
    if request.post?
      current_user.reported_caregivers << @caregiver
      current_user.save
      modified_name = params[:name]
      modified_lastname = params[:lastname]
      modified_phone = params[:phone]
      modified_mail = params[:mail]
      mensaje= params[:mensaje]
      omd_notifications_mail= "vete0hmydog@gmail.com"

      dni = user.dni
      AdminMailer.caregiver_report_by_email(@caregiver, modified_name, modified_lastname, modified_phone, modified_mail, omd_notifications_mail, mensaje, dni).deliver_later

      redirect_to index_user_caregiver_path, notice: 'Reporte enviado.'
    end
  end

  def solicitar
    @caregiver = Caregiver.find(params[:id])
    if user_signed_in?
      user = User.find(current_user.id)
      dni = user.dni
      @name = user.name
      @lastname = user.surname
      @phone = user.phoneNum
      @mail = user.email
    else
      @name = " "
      @lastname = " "
      @phone = " "
      @mail = " "
    end

    if request.post?
      if user_signed_in?
        current_user.caregivers << @caregiver
        current_user.save
      end
      modified_name = params[:name]
      modified_lastname = params[:lastname]
      modified_phone = params[:phone]
      modified_mail = params[:mail]
      caremail= @caregiver.email
      mensaje= params[:mensaje]
      omd_notifications_mail= "vete0hmydog@gmail.com"

      UserMailer.caregiver_notify_by_email(modified_name, modified_lastname, modified_phone, modified_mail, caremail, mensaje).deliver_later
      AdminMailer.caregiver_notify_by_email(@caregiver, modified_name, modified_lastname, modified_phone, modified_mail, omd_notifications_mail, mensaje, dni).deliver_later

      redirect_to index_user_caregiver_path, notice: 'Servicio solicitado exitosamente, espere el contacto a traves de su correo electrónico o teléfono!'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caregiver
      @caregiver = Caregiver.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def caregiver_params
      params.require(:caregiver).permit(:name, :surname, :phoneNum, :email, :zone, :services)
    end


end

app/helpers/caregivers_helper.rb
module CaregiversHelper
end

app/views/caregivers/_caregiver.html.erb
<div class="card-body">
  <p class="card-text"><strong>Zona: </strong><%= caregiver.zone %></p>   
  <p  class="card-text"><strong>Servicios: </strong><%= caregiver.services %></p>
  <p class="card-text"><strong>Correo: </strong><%= caregiver.email %></p>   
  <p  class="card-text"><strong>Teléfono: </strong><%= caregiver.phoneNum %></p>
</div>

app/views/caregivers/_form.html.erb
<div class=""> 
  <div class="container">
    <div class="d-flex justify-content-center align-items-center mt-4">
      <div class="col-md-7 col-lg-8">
        <h4 class="mb-3">Datos del cuidador</h4>
        <%= form_with(model: caregiver) do |f| %>
          <div class="row g-3">
            <div class="col-sm-6">
               <%= f.label :Nombre, class:"form-label" %>
               <%= f.text_field :name, autofocus: true, autocomplete: "name", class:"form-control", placeholder:"", required: "required"%>
            </div>

            <div class="col-sm-6">
               <%= f.label :Apellido, class:"form-label" %>
               <%= f.text_field :surname, autofocus: true, autocomplete: "surname", class:"form-control", placeholder:"", required: "required"%>
            </div>

            <div class="col-sm-6">
               <%= f.label :Zona, class:"form-label" %>
               <%= f.text_field :zone, autofocus: true, autocomplete: "zone", class:"form-control", placeholder:"", required: "required"%>
            </div>

            <div class="col-sm-6">
               <%= f.label :Servicios, class:"form-label" %>
               <%= f.text_field :services, autofocus: true, autocomplete: "services", class:"form-control", placeholder:"", required: "required"%>
            </div>

            <div class="row g-3">
              <div class="col-sm-12">
                <%= f.label :Correo, class:"form-label" %>
                <%= f.text_field :email, autofocus: true, autocomplete: "email", class:"form-control", placeholder:"", required: "required"%>
              </div>
            </div>

            <div class="row g-3">
              <div class="col-sm-12">
                <%= f.label :Teléfono, class:"form-label" %>
                <%= f.text_field :phoneNum, autofocus: true, autocomplete: "phoneNum", class:"form-control", placeholder:"", required: "required"%>
              </div>
            </div>

          </div>

          <% if flash[:alert] %>
            <div class="alert alert-danger my-2 p-1 text-center">
              <%= flash[:alert] %>
            </div>
          <% end %>   

          <% if caregiver.errors.any? %>
            <div class="alert alert-danger my-2 p-1 text-center">
              <ul>
                <% caregiver.errors.each do |error| %>
                  <li><%= error.message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <hr class="mt-4">
          <%= f.submit "Agregar", class:"w-100 btn btn-primary btn-lg" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/caregivers/confirm_delete.html.erb
<div class="container-fluid mt-4 px-2">
  <div class="modal modal-sheet position-static d-block p-4 py-md-2" tabindex="-1" role="dialog" id="modalSheet">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-4 shadow">
        <div class="modal-header border-bottom-0">
          <h2 class="modal-title fs-5 ">Confirmar eliminación</h2>
        </div>
        <div class="modal-body py-0">
            <p>¿Estás seguro de que deseas eliminar al cuidador <%= @caregiver.surname%> <%= @caregiver.name %>?</p>
        </div>
        <div class="modal-footer flex-column align-items-stretch w-100 pb-3 border-top-0">
          <%= button_to "Confirmar", @caregiver, method: :delete, class:'btn btn-danger w-100' %>
          <%= link_to "Volver atras", caregiver_path, class:"btn btn-outline-secondary" %>
        </div>     
      </div>
    </div>
  </div>
</div>

app/views/caregivers/edit.html.erb
<div class="container-fluid mt-4 px-2">
  <h2>Editar cuidador</h2>
  <hr>
  <%= render "form", caregiver: @caregiver %>

  <div class=""> 
    <div class="container">
      <div class="d-flex justify-content-center align-items-center mt-4">
        <div class="col-md-7 col-lg-8">
          <%= link_to "Volver atras", @caregiver, class: "btn btn-lg btn-outline-secondary w-100 mt-0 mb-4"%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/caregivers/index.html.erb
<div class="container-fluid mt-4 px-2">
  <h2>Cuidadores</h2>
  <hr>
  <% if user_signed_in? == false %>
    <%= link_to "Volver atras", root_path, class:"btn btn-outline-secondary px-3 mb-2"%>
  <% end %>
  <% if user_signed_in? %>
    <%= link_to "Agregar cuidador", new_caregiver_path, class:"btn btn-primary px-3 mb-2"%>
  <% end %>
  <% if flash[:alert].present? %>
    <div class="alert alert-danger">  
      <%= flash[:alert] %>
    </div>
  <% elsif flash[:notice].present? %>
    <div class="alert alert-success">  
      <%= flash[:notice] %>
    </div>
  <% end %>
  
<div class="my-3" id="caregivers">
    <div class="row">
      <% if @caregivers.present? %>
        <% @caregivers.each do |caregiver| %>
          <div class="col-lg-4 col-md-6 col-sm-12 mb-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title mb-2"><%= caregiver.name + ' ' + caregiver.surname %></h5>
                        <p class="card-text"><strong>Zona: </strong><%= caregiver.zone %></p>
                        <p class="card-text"><strong>Servicios: </strong><%= caregiver.services %></p>
                        <p class="card-text"><strong>Teléfono: </strong><%= caregiver.phoneNum %></p>
                        <p class="card-text"><strong>Correo: </strong><%= caregiver.email %></p>                         
                    </div>
                    <div class = card-body>
                        <button class="btn btn-secondary d-inline-flex justify-content-center align-items-center" type="button" data-bs-toggle="modal" data-bs-target="#show_request"><%= link_to "SELECCIONAR", caregiver, class:"text-white text-decoration-none pe-2"%><i class="bi bi-plus-circle align-items-center mx-1"></i></button>
                    </div>
                </div>
            </div>
        <% end %>
      <% else %>
        <div class="col-12">
          <p>No hay cuidadores cargados en la aplicación.</p>
        </div>
      <% end %>
    </div>
</div>   

app/views/caregivers/index_user.html.erb
<div class="container-fluid mt-4 px-2">
  <h2>Cuidadores</h2>
  <hr>
  <% if user_signed_in? == false %>
    <%= link_to "Volver atras", root_path, class:"btn btn-outline-secondary px-3 mb-2"%>
  <% end %>
  <% if flash[:alert].present? %>
    <div class="alert alert-danger">  
      <%= flash[:alert] %>
    </div>
  <% elsif flash[:notice].present? %>
    <div class="alert alert-success">  
      <%= flash[:notice] %>
    </div>
  <% end %>


  <div class="my-3" id="caregivers">
    <p class="text-muted"><%= message= 'Desde OhMyDog sabemos lo mucho que quiere a su mascota ¡Es parte de la familia! y es por eso mismo que, CADA CUIDADOR/A presente en este listado es previamente ESTUDIADO Y ELEGIDO cuidadosamente por nosotros con la intención de ofrecerle a usted el mejor servicio posible para su amigo peludo.' %></p>
    <div class="row">
      <% if @caregivers.present? %>
        <% @caregivers.each do |caregiver| %>
          <div class="col-lg-4 col-md-6 col-sm-12 mb-3">
            <div class="card">
              <div class="card-body">
                <p class="card-text"><strong>Nombre: </strong><%= caregiver.name %></p>
                <p class="card-text"><strong>Apellido: </strong><%= caregiver.surname %></p>
                <p class="card-text"><strong>Zona: </strong><%= caregiver.zone %></p>
                <p class="card-text"><strong>Servicios: </strong><%= caregiver.services %></p>
              </div>
              <div class="card-footer">
                <div class="d-flex justify-content-between">
                  <% if !user_signed_in?%>
                    <%= link_to "Contactar", solicitar_cuidador_path(caregiver), class: "btn btn-primary w-20"%>
                  <% elsif current_user.caregivers.include?(caregiver) %>
                    <% unless current_user.reported_caregivers.include?(caregiver) %>
                      <%= link_to "Reportar", reportar_cuidador_path(caregiver), class: "btn btn-danger" %>
                    <% end %>
                  <% else %>
                    <%= link_to "Contactar", solicitar_cuidador_path(caregiver), class: "btn btn-primary w-20"%>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="col-12">
          <p>No hay cuidadores disponibles por el momento.</p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/caregivers/new.html.erb
<div class="container-fluid mt-4 px-2">
  <h2>Agregar cuidador</h2>
  <hr>
  <%= render "form", caregiver: @caregiver %>

  <div class=""> 
    <div class="container">
      <div class="d-flex justify-content-center align-items-center mt-4">
        <div class="col-md-7 col-lg-8">
          <%= link_to "Volver atras", caregivers_path, class: "btn btn-lg btn-outline-secondary w-100 mt-0 mb-4"%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/caregivers/reportar.html.erb
<div class="container-fluid mt-4 px-2">
  <h2>Reportar</h2>
  <hr>
  <p class="text-muted">
    <%= message = 'Lamentamos oír que tuviste problemas con ' + @caregiver.name + '. En OhMyDog nos tomamos los reclamos MUY en serio, por favor describe qué sucedió.' %>
  </p>
  <%= form_with(method: :post) do |f|  %>

    <div class="col-12">
        <%= f.label :Describe_el_motivo, class:"form-label" %>
        <%= f.text_field :mensaje, class: "form-control", placeholder: "", required: "required" %>
    </div>
    <hr>

    <h5>Confirme sus datos:</h5>
    <div class="row g-3">
      <div class="col-sm-6">
        <%= f.label :Nombre, class:"form-label" %>
        <%= f.text_field :name, autofocus: true, autocomplete: "name", class:"form-control", placeholder:"", value:@name, required: "required", disabled: true%>
      </div>

      <div class="col-sm-6">
        <%= f.label :Apellido, class:"form-label" %>
        <%= f.text_field :lastname, autofocus: true, autocomplete: "lastname", class:"form-control", placeholder:"", value:@lastname, required: "required", disabled: true%>
      </div>
              
      <div class="col-12">
        <%= f.label :'Correo electronico', class:"form-label" %>
        <%= f.email_field :mail, autofocus: true, autocomplete: "mail", class:"form-control", placeholder:"", value:@mail, required: "required"%>
      </div>
            
      <div class="col-12">
        <%= f.label :Telefono, class:"form-label" %>
        <%= f.telephone_field :phone, autofocus: true, autocomplete: "phone", class:"form-control", placeholder:"", value:@phone, required: "required"%>
      </div>
    

      <% if flash[:alert] %>
        <div class="alert alert-danger my-2 p-1 text-center">
          <%= flash[:alert] %>
        </div>
      <% end %>   

      <hr class="mt-3 mb-1">
      <div class="col-sm-6">
        <%= f.submit "Enviar", class:"w-100 btn btn-lg btn-primary" %>
      </div>
      <div class="col-sm-6">
        <%= link_to "Volver atras", index_user_caregiver_path, class:"w-100 btn btn-lg btn-outline-secondary"%>
      </div>
    </div>
  <% end %>
</div>

app/views/caregivers/show.html.erb
<div class="modal modal-sheet position-static d-block p-0 py-md-0 my-0" tabindex="-1" role="dialog" id="modalTour">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-4 shadow">
      <div class="modal-body p-5">
        <h2 class="fw-bold mb-0 fs-3 text-center"> <%= @caregiver.name + ' ' + @caregiver.surname %> </h2>
        <div class="text-center my-3">
          <%= render @caregiver %>
        </div>
        <div class="row g-3 text-center pb-2">
          <div class="col-6">
            <%= link_to "Editar", edit_caregiver_path(@caregiver), class: "btn btn-primary w-100"%>
          </div>
          <div class="col-6">
            <%= link_to "Eliminar", confirm_delete_caregiver_path(@caregiver), class: "btn btn-danger w-100" %>
          </div>
          <div class="col-6">
              <%= link_to "Volver atras", caregivers_path, class: "btn btn-outline-secondary w-100 "%>
          </div>  
        </div>
      </div>
    </div>
  </div>
</div>

app/views/caregivers/solicitar.html.erb
<div class="container-fluid mt-4 px-2">
  <h2>Solicitud servicio de cuidado canino</h2>
  <hr>
  <p><strong>Datos de contacto</strong></p>
  <%= form_with(method: :post) do |f|  %>
    <div class="row g-3">

      <% if user_signed_in? %>
      
        <div class="col-sm-6">
          <%= f.label :Nombre, class:"form-label" %>
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class:"form-control", placeholder:"", value:@name, required: "required", disabled: true%>
        </div>

        <div class="col-sm-6">
          <%= f.label :Apellido, class:"form-label" %>
          <%= f.text_field :lastname, autofocus: true, autocomplete: "lastname", class:"form-control", placeholder:"", value:@lastname, required: "required", disabled: true%>
        </div>

      <% else %>

        <div class="col-sm-6">
          <%= f.label :Nombre, class:"form-label" %>
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class:"form-control", placeholder:"", value:@name, required: "required"%>
        </div>

        <div class="col-sm-6">
          <%= f.label :Apellido, class:"form-label" %>
          <%= f.text_field :lastname, autofocus: true, autocomplete: "lastname", class:"form-control", placeholder:"", value:@lastname, required: "required"%>
        </div>

      <% end %>

              
      <div class="col-12">
        <%= f.label :'Correo electronico', class:"form-label" %>
        <%= f.email_field :mail, autofocus: true, autocomplete: "mail", class:"form-control", placeholder:"", value:@mail, required: "required"%>
      </div>
            
      <div class="col-12">
        <%= f.label :Telefono, class:"form-label" %>
        <%= f.telephone_field :phone, autofocus: true, autocomplete: "phone", class:"form-control", placeholder:"", value:@phone, required: "required"%>
      </div>
    

    <div class="col-12">
        <%= f.label :mensaje, class: "form-label" %>
        <%= f.text_field :mensaje, class: "form-control", placeholder: "" %>
    </div>

      <% if flash[:alert] %>
        <div class="alert alert-danger my-2 p-1 text-center">
          <%= flash[:alert] %>
        </div>
      <% end %>   

      <hr class="mt-3 mb-1">
      <div class="col-sm-6">
        <%= f.submit "Contactar", class:"w-100 btn btn-primary btn-lg" %>
      </div>
      <div class="col-sm-6">
      <%= link_to "Volver atras", index_user_caregiver_path, class:"w-100 btn btn-outline-secondary btn-lg"%>
      </div>
    </div>
  <% end %>
</div>