config/routes.rb
Rails.application.routes.draw do

  resources :missing_posts
  resources :donations do
    post 'donate', on: :collection
    member do
      get 'confirm_donate'
      get 'confirm_delete'
    end
  end


  resources :vacunas, only: [:new, :create, :edit, :edit2, :update, :destroy] do
    member do
      get 'confirm_delete'
      get 'confirm_delete2'
      get 'edit2'
      post 'edit2'
    end
  end

  get '/download_HistoriaClinica/:dog_id(.:format)', to: 'medical_stories#downloadHC', as: 'download_historia_clinica', defaults: { format: :pdf }
  get '/download_LibretaSanitaria/:dog_id(.:format)', to: 'health_records#downloadLS', as: 'download_libreta_sanitaria', defaults: { format: :pdf }

  resources :health_records do
  end
  
  resources :medical_stories do
  end

  resources :dogs do
    member do
      get 'confirm_delete'
    end
  end
  resources :registers, only: [:index, :new, :create]
  resources :admin_registers, only: [:index, :new, :create]
  get 'dashboard/home'
  root 'homepage#home'

  devise_for :users, skip: [:registrations], controllers: { sessions:'users/sessions'}

  # Rutas para editar usuario y otras funcionalidades proporcionadas por Devise
  resources :users, only: [:edit, :update] do
    member do
      get 'user_dogs', to: 'dogs#index_user_dogs', as: 'user_dogs'
    end
  end

  # Rutas personalizadas para el registro de usuario
  get "/registers", to: "registers#new", as: :new_user_registration
  post "/registers", to: "registers#create", as: :user_registration
  # Rutas para editar y actualizar la contraseña
  get "/registers/edit/:id", to: "registers#edit", as: :edit_user_registration
  patch "/registers/update/:id", to: "registers#update", as: :update_user_registration

  # Rutas de cuidadores y paseadores
  resources :caregivers do
    member do
      get 'confirm_delete'
    end
  end
  get '/u/caregivers', to: 'caregivers#index_user', as: :index_user_caregiver
  post 'u/caregivers/:id/request', to: 'caregivers#solicitar'
  get 'u/caregivers/:id/request', to: 'caregivers#solicitar', as: :solicitar_cuidador
  post 'u/caregivers/:id/report', to: 'caregivers#reportar'
  get 'u/caregivers/:id/report', to: 'caregivers#reportar', as: :reportar_cuidador

  resources :walkers do
    member do
      get 'confirm_delete'
    end
  end
  get '/u/walkers', to: 'walkers#index_user', as: :index_user_walker
  post 'u/walkers/:id/request', to: 'walkers#solicitar'
  get 'u/walkers/:id/request', to: 'walkers#solicitar', as: :solicitar_paseador
  post 'u/walkers/:id/report', to: 'walkers#reportar'
  get 'u/walkers/:id/report', to: 'walkers#reportar', as: :reportar_paseador

  resources :medical_story do
    member do
      get 'confirm_delete'
    end
  end

  resources :health_record do
    member do
      get 'confirm_delete'
    end
  end

  # Rutas turnos "Santi"

  resources :appointments do
    member do
      get 'confirm_delete'
    end
  end

  patch 'appointments/:id/confirm_user_edit', to: 'appointments#confirm_user_edit', as: 'confirm_user_edit'

  patch 'appointments/:id/confirm_admin_edit', to: 'appointments#confirm_admin_edit', as: 'confirm_admin_edit'

  patch 'confirmed/:id/remove_cancel', to: 'appointments#remove_cancel', as: 'remove_cancel'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/:id/confirm_cancel', to: 'appointments#confirm_cancel', as: :confirm_cancel_appointment
  get '/:id/edit', to: 'appointments#edit', as: :edit__appointment

  get '/requests', to: 'appointments#index_requests', as: :requests
  get '/requests/:id', to: 'appointments#show_request', as: :request

  get '/confirmed', to: 'appointments#index_confirmed', as: :confirmed
  get '/confirmed/:id', to: 'appointments#show_confirmed', as: :confirmed_show


  resources :adoptions do
    member do
      patch 'confirm'
      get 'confirm_delete'
    end
  end

  post 'adoption/:id/request', to: 'adoptions#solicitar'
  get 'adoption/:id/request', to: 'adoptions#solicitar', as: :solicitar

  resources :missing_posts do
    member do
      patch 'confirm'
      get 'confirm_delete'
    end
  end

  post 'missing_post/:id/request', to: 'missing_posts#solicitar'
  get 'missing_post/:id/request', to: 'missing_posts#solicitar', as: :mp_solicitar

end

app/models/donation.rb
class Donation < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
    validates :closing_date, presence: true
    validate :closing_date_cannot_be_in_the_past_or_present
    validates :target_amount, presence: true, numericality: { greater_than: 0, message: 'El valor ingresado no es valido'}
    validates :amount, numericality: { greater_than: 0, message: 'El valor ingresado no es valido' }, allow_nil: true

    private
    def closing_date_cannot_be_in_the_past_or_present
        if closing_date.present? && closing_date <= Date.current
            errors.add(:closing_date, 'La fecha ingresada no es valida, asegúrese de que sea una fecha futura.')
        end
    end

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  # require 'mercadopago'

  before_action :authenticate_user!, except: [:index, :donate, :confirm_donate]
  before_action :authenticate_admin, only: [:show, :new, :create, :edit, :update, :destroy, :confirm_delete]
  before_action :set_donation, only: %i[ show edit update destroy]

  # GET /donations or /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1 or /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations or /donations.json
  def create
    @donation = Donation.new(donation_params)

    respond_to do |format|
      if @donation.save
        format.html { redirect_to donation_url(@donation), notice: "La publicación de donación se creó con éxito." }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1 or /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to donation_url(@donation), notice: "La publicación donación se actualizó correctamente." }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end  
  end

  # DELETE /donations/1 or /donations/1.json
  def destroy
    @donation.destroy

    respond_to do |format|
      format.html { redirect_to donations_url, notice: "La publicación de donación fue eliminada con éxito." }
      format.json { head :no_content }
    end
  end

  def confirm_delete
    @donation = Donation.find(params[:id])
  end

  def donate
    # SDK de Mercado Pago
    require 'mercadopago'
    # Agrega credenciales
    @sdk = Mercadopago::SDK.new(ENV['MERCADOPAGO_ACCESS_TOKEN'])

    # Obtén el monto de la donación desde los parámetros del formulario
    amount = params[:amount].to_f
     # Obtén el título de la publicación desde los parámetros del formulario
    donation_title = params[:donation_title] || "Colaboración a campaña de donación"

    preference_response = @sdk.preference.create(preference_params(donation_title, amount))
    @preference_id = preference_response[:response]['id']
    puts "Preference ID: #{@preference_id}"
    redirect_to confirm_donate_donation_path(id: @preference_id)

    #preference = preference_response[:response]

    # Este valor substituirá a string "<%= @preference_id %>" no seu HTML
    #@preference_id = preference['id'] 

    # Redirige al usuario a la página de pago de MercadoPago
    # redirect_to preference['sandbox_init_point'],allow_other_host: true
    #redirect_to confirm_donate_donation_path(id: @preference_id )
  end

  def confirm_donate
    # Verifica que @sdk esté inicializado antes de usarlo
    if @sdk.nil?
      # Puedes inicializar @sdk aquí si no lo has hecho ya
      @sdk = Mercadopago::SDK.new(ENV['MERCADOPAGO_ACCESS_TOKEN'])
    end
    # Usa @sdk para acceder a la variable de instancia definida en donate
    preference_response = @sdk.preference.get(params[:id])
    preference = preference_response[:response]
    @donation_title = preference['items'].first['title']
    @amount = preference['items'].first['unit_price']
    @sandbox_init_point = preference['sandbox_init_point']
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def donation_params
      params.require(:donation).permit(:title, :description, :closing_date, :target_amount)
    end

    def preference_params(donation_title, amount)
      {
        items: [{
          title: donation_title,
          quantity: 1,
          currency_id: 'ARS', # Puedes ajustar la moneda según tu necesidad
          unit_price: amount
        }]
      }
    end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_donation.html.erb
<div class="card-body">
  <h5 class="card-title  text-center"><%= donation.title %></h5>
  <hr>
  <p class="card-text"><strong>Descripcion: </strong><%= donation.description %></p>   
  <p class="card-text"><strong>Fecha limite: </strong><%= donation.closing_date.strftime('%d/%m/%Y') %></p>
  <p  class="card-text"><strong>Monto a alcanzar: </strong> <%= number_to_currency(donation.target_amount, separator: ',', delimiter: '.') %>

app/views/donations/_form.html.erb
<div class=""> 
  <div class="container">
    <div class="d-flex justify-content-center align-items-center mt-4">
      <div class="col-md-7 col-lg-8">
        <%= form_with(model: donation) do |form| %>
          <div class="row g-3">
            <div class="col-12">
              <%= form.label :Titulo, class:"form-label" %>
              <%= form.text_field :title, autofocus: true, autocomplete: "title", class:"form-control", placeholder:"", required: "required"%>
            </div>

            <div class="col-12">
              <%= form.label :"Descripción", class:"form-label" %>
              <%= form.text_field :description, autofocus: true, autocomplete: "description", class:"form-control", placeholder:"", required: "required"%>
            </div>
                  
            <div class="col-sm-6">
              <%= form.label :'Fecha_limite', class:"form-label" %>
              <%= form.date_field :closing_date, class: "form-control form-control-inline" %> 
            </div>
              
            <div class="col-sm-6">
              <%= form.label :'Monto objetivo', class:"form-label" %>
              <div class="input-group mb-3">
                <span class="input-group-text">$</span>
                <%= form.text_field :target_amount, autofocus: true, autocomplete: "target_amount", class: "form-control", aria_label: "Amount (to the nearest dollar)" %>
              </div>
            </div>

            <hr class="my-2">

            <% if @donation.errors.any? %>
              <div class="alert alert-danger w-100" role="alert">
                <ul class="list-unstyled">
                  <% @donation.errors.each do |error| %>
                    <li><%= error.message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            
            <div class="col-sm-6">
              <%= form.submit "Cargar campaña", class:"w-100 btn btn-primary" %>
            </div>

            <div class="col-sm-6">
              <%= link_to "Volver atras", donations_path, class: "btn btn-outline-secondary w-100"%>
            </div>
          </div>    
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/donations/confirm_delete.html.erb
<div class="container-fluid mt-4 px-2">
  <div class="modal modal-sheet position-static d-block p-4 py-md-2" tabindex="-1" role="dialog" id="modalSheet">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-4 shadow">
        <div class="modal-header border-bottom-0">
          <h2 class="modal-title fs-5 ">Confirmar eliminación</h2>
        </div>
        <div class="modal-body py-0">
            <p>¿Estás seguro de que deseas eliminar la publicacion de la campaña de donacion <%= @donation.title%>?</p>
        </div>
        <div class="modal-footer flex-column align-items-stretch w-100 pb-3 border-top-0">
          <%= button_to "Confirmar", @donation, method: :delete, class:'btn btn-danger w-100' %>
          <%= link_to "Volver atras", donation_path, class:"btn btn-outline-secondary" %>
        </div>     
      </div>
    </div>
  </div>
</div>

app/views/donations/confirm_donate.html.erb
<div class="container-fluid mt-4 px-2">
  <div class="modal modal-sheet position-static d-block p-4 py-md-2" tabindex="-1" role="dialog" id="modalSheet">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-4 shadow">
        <div class="modal-header border-bottom-0">
          <h2 class="modal-title fs-5 ">Confirmar donación</h2>
        </div>
        <div class="modal-body py-0">
            <p>Tu donación sera a <%= @donation_title %> con un monto de $<%= @amount %></p>
        </div>
        <div class="modal-footer flex-column align-items-stretch w-100 pb-3 border-top-0">
          <%= link_to "Pagar a través de MercadoPago", "javascript:void(0);", class: "btn btn-primary", id: "mercadoPagoLink" %>
          <script>
            document.getElementById("mercadoPagoLink").addEventListener("click", function() {
              // Abre la ventana externa de MercadoPago
              window.open("<%= @sandbox_init_point %>", "_blank");

              // Redirige a la página de índice del controlador donations después de un breve retraso
              setTimeout(function() {
                window.location.href = "<%= donations_path %>";
              }, 100);
            });
          </script>
          <%= link_to "Cancelar", donations_path, class:"btn btn-outline-danger" %>
        </div>     
      </div>
    </div>
  </div>
</div>

app/views/donations/edit.html.erb
<div class="container-fluid py-3">
    <h2>Editar campaña de donación</h2>
    <hr>
    <%= render "form", donation: @donation %>
</div>

app/views/donations/index.html.erb
<div class="container-fluid mt-4 px-2">
  <h2>Campañas de donaciones</h2>
  <hr>
  <div>
    <% if user_signed_in? == false %>
      <%= link_to "Volver atras", root_path, class:"btn btn-outline-secondary px-3 mb-2"%>
    <% elsif current_user.admin?%>
      <%= link_to "Agregar donación", new_donation_path, class:"btn btn-primary me-2 mb-2" %>
    <% end %>
  </div>

  <% if flash[:alert].present? %>
    <div class="alert alert-danger">  
      <%= flash[:alert] %>
    </div>
  <% elsif flash[:notice].present? %>
    <div class="alert alert-success">  
      <%= flash[:notice] %>
    </div>
  <% end %>

  <div class="my-3" id="donations">
    <div class="row">
      <% if @donations.present? == false %>
        <p>Por el momento no hay publicadas campañas de donacion.</p>
      <% end %>
      <% @donations.each do |donation| %>        
        <div class="col-lg-4 col-md-6 col-sm-12 mb-3">
          <div class="card">
            <%= render donation %>
              <div class="text-center">
                <% if user_signed_in? == false || current_user.role == 'user' %>
                  <%= form_tag donate_donations_path, method: :post do %>
                    <%= hidden_field_tag 'donation_title', donation.title %>
                    <div class="input-group w-100 mb-3">
                      <span class="input-group-text">$</span>
                      <%= text_field_tag :amount, nil, type: "text", autofocus: true, autocomplete: "amount", class: "form-control", aria_label: "Amount (to the nearest dollar)", oninput: "handleDecimalInput(this)" %>
                      <%= submit_tag "Donar", class: "btn btn-success" %>
                      
                    </div>
                  <% end %>
                <% else %>
                  <%= link_to "Ver mas", donation, class:"btn btn-outline-secondary" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  function handleDecimalInput(input) {
    // Reemplaza las comas con puntos en el valor del campo
    input.value = input.value.replace(',', '.');
   }
</script>

app/views/donations/new.html.erb
<div class="container-fluid py-3">
    <h2>Nueva campaña de donación</h2>
    <hr>
    <%= render "form", donation: @donation %>
</div>

app/views/donations/show.html.erb
<div class="modal modal-sheet position-static d-block p-0 py-md-0 my-5" tabindex="-1" role="dialog" id="modalTour">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-4 shadow">
      <div class="modal-body p-3">
        <div class="text-center my-3">
          <%= render @donation %>
        </div>
        <div class="row g-3 text-center mt-2">
          <% if current_user.admin? %>
            <div class="col-6">
              <%= link_to "Editar", edit_donation_path(@donation), class: "btn btn-primary w-100" %>
            </div>
            <div class="col-6">
              <%= link_to "Eliminar", confirm_delete_donation_path(@donation), class: "btn btn-danger w-100" %>
            </div>
          <% end %>
          <div class="col-6">
            <%= link_to "Volver atras", donations_path, class: "btn btn-outline-secondary w-100" %>
          </div>
        </div>  
      </div>
    </div>
  </div>
</div>