config/routes.rb
Rails.application.routes.draw do

  resources :missing_posts
  resources :donations do
    post 'donate', on: :collection
    member do
      get 'confirm_donate'
      get 'confirm_delete'
    end
  end


  resources :vacunas, only: [:new, :create, :edit, :edit2, :update, :destroy] do
    member do
      get 'confirm_delete'
      get 'confirm_delete2'
      get 'edit2'
      post 'edit2'
    end
  end

  get '/download_HistoriaClinica/:dog_id(.:format)', to: 'medical_stories#downloadHC', as: 'download_historia_clinica', defaults: { format: :pdf }
  get '/download_LibretaSanitaria/:dog_id(.:format)', to: 'health_records#downloadLS', as: 'download_libreta_sanitaria', defaults: { format: :pdf }

  resources :health_records do
  end
  
  resources :medical_stories do
  end

  resources :dogs do
    member do
      get 'confirm_delete'
    end
  end
  resources :registers, only: [:index, :new, :create]
  resources :admin_registers, only: [:index, :new, :create]
  get 'dashboard/home'
  root 'homepage#home'

  devise_for :users, skip: [:registrations], controllers: { sessions:'users/sessions'}

  # Rutas para editar usuario y otras funcionalidades proporcionadas por Devise
  resources :users, only: [:edit, :update] do
    member do
      get 'user_dogs', to: 'dogs#index_user_dogs', as: 'user_dogs'
    end
  end

  # Rutas personalizadas para el registro de usuario
  get "/registers", to: "registers#new", as: :new_user_registration
  post "/registers", to: "registers#create", as: :user_registration
  # Rutas para editar y actualizar la contraseña
  get "/registers/edit/:id", to: "registers#edit", as: :edit_user_registration
  patch "/registers/update/:id", to: "registers#update", as: :update_user_registration

  # Rutas de cuidadores y paseadores
  resources :caregivers do
    member do
      get 'confirm_delete'
    end
  end
  get '/u/caregivers', to: 'caregivers#index_user', as: :index_user_caregiver
  post 'u/caregivers/:id/request', to: 'caregivers#solicitar'
  get 'u/caregivers/:id/request', to: 'caregivers#solicitar', as: :solicitar_cuidador
  post 'u/caregivers/:id/report', to: 'caregivers#reportar'
  get 'u/caregivers/:id/report', to: 'caregivers#reportar', as: :reportar_cuidador

  resources :walkers do
    member do
      get 'confirm_delete'
    end
  end
  get '/u/walkers', to: 'walkers#index_user', as: :index_user_walker
  post 'u/walkers/:id/request', to: 'walkers#solicitar'
  get 'u/walkers/:id/request', to: 'walkers#solicitar', as: :solicitar_paseador
  post 'u/walkers/:id/report', to: 'walkers#reportar'
  get 'u/walkers/:id/report', to: 'walkers#reportar', as: :reportar_paseador

  resources :medical_story do
    member do
      get 'confirm_delete'
    end
  end

  resources :health_record do
    member do
      get 'confirm_delete'
    end
  end

  # Rutas turnos "Santi"

  resources :appointments do
    member do
      get 'confirm_delete'
    end
  end

  patch 'appointments/:id/confirm_user_edit', to: 'appointments#confirm_user_edit', as: 'confirm_user_edit'

  patch 'appointments/:id/confirm_admin_edit', to: 'appointments#confirm_admin_edit', as: 'confirm_admin_edit'

  patch 'confirmed/:id/remove_cancel', to: 'appointments#remove_cancel', as: 'remove_cancel'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/:id/confirm_cancel', to: 'appointments#confirm_cancel', as: :confirm_cancel_appointment
  get '/:id/edit', to: 'appointments#edit', as: :edit__appointment

  get '/requests', to: 'appointments#index_requests', as: :requests
  get '/requests/:id', to: 'appointments#show_request', as: :request

  get '/confirmed', to: 'appointments#index_confirmed', as: :confirmed
  get '/confirmed/:id', to: 'appointments#show_confirmed', as: :confirmed_show


  resources :adoptions do
    member do
      patch 'confirm'
      get 'confirm_delete'
    end
  end

  post 'adoption/:id/request', to: 'adoptions#solicitar'
  get 'adoption/:id/request', to: 'adoptions#solicitar', as: :solicitar

  resources :missing_posts do
    member do
      patch 'confirm'
      get 'confirm_delete'
    end
  end

  post 'missing_post/:id/request', to: 'missing_posts#solicitar'
  get 'missing_post/:id/request', to: 'missing_posts#solicitar', as: :mp_solicitar

end

app/models/missing_post.rb
class MissingPost < ApplicationRecord
    belongs_to :user
    validates :name, presence: true
    validates :breed, presence: true
    validates :gender, presence: true
    validates :description, presence: true
    validates :age, presence: true
    validates :size, presence: true
    validates :zone, presence: true
    has_one_attached :image
  end

app/controllers/missing_posts_controller.rb
class MissingPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :solicitar]
  before_action :require_owner_or_admin, only: [:edit, :update, :confirm, :destroy, :confirm_delete]
  before_action :set_missing_post, only: %i[ show edit update destroy ]

  # GET /missing_posts or /missing_posts.json
  def index
    @missing_posts = MissingPost.order(created_at: :desc) # MAS RECIENTE AL MAS VIEJO
    @finished_missing_posts = @missing_posts.select { |missing_post| missing_post.finished? }

    if @finished_missing_posts.count >= 5
      @finished_missing_posts = @finished_missing_posts.sort_by { |missing_post| missing_post.confirmed_at }
      @finished_missing_posts.reverse!
      excess_missing_posts = @finished_missing_posts[5..-1]
      excess_missing_posts.each do |missing_post|
        missing_post.destroy
      end
    end
  end

  def confirm
    @missing_post = MissingPost.find(params[:id])
    @missing_post.update(missing_post_params)
    redirect_to @missing_post
  end

  # GET /missing_posts/1 or /missing_posts/1.json
  def show

  end

  # GET /missing_posts/new
  def new
    @missing_post = MissingPost.new
  end

  # GET /missing_posts/1/edit
  def edit

  end

  # POST /missing_posts or /missing_posts.json
  def create
    @missing_post = MissingPost.new(missing_post_params)
    @missing_post.user_id = current_user.id
    if @missing_post.name.blank?
      @missing_post.name= "Sin nombre"
    end
    respond_to do |format|
      if @missing_post.save
        format.html { redirect_to missing_post_url(@missing_post), notice: "Publicación exitosa." }
        format.json { render :show, status: :created, location: @missing_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @missing_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /missing_posts/1 or /missing_posts/1.json
  def update
    respond_to do |format|
      if @missing_post.update(missing_post_params)
        format.html { redirect_to missing_post_url(@missing_post), notice: "Publicación editada." }
        format.json { render :show, status: :ok, location: @missing_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @missing_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /missing_posts/1 or /missing_posts/1.json
  def destroy
    @missing_post.destroy

    respond_to do |format|
      format.html { redirect_to missing_posts_url, notice: "Publicación eliminada." }
      format.json { head :no_content }
    end
  end

  def confirm_delete

  end

  def solicitar
    @missing_post = MissingPost.find(params[:id])

    if user_signed_in?
      user = User.find(current_user.id)
      @name = user.name
      @lastname = user.surname
      @phone = user.phoneNum
      @mail = user.email
    else
      @name = ""
      @lastname = ""
      @phone = ""
      @mail = ""
    end

    if request.post?
      modified_name = params[:name]
      modified_lastname = params[:lastname]
      modified_phone = params[:phone]
      modified_mail = params[:mail]
      dogname= @missing_post.name
      dogmail= User.find(@missing_post.user_id).email
      omd_notifications_mail= "vete0hmydog@gmail.com" #PREGUNTAR SI TIENEN ALGUNO

      UserMailer.contact_by_email(modified_name, modified_lastname, modified_phone, modified_mail, dogname, dogmail).deliver_later

      if user_signed_in?
        dni = User.find(current_user.id).dni
      else
        dni = -1
      end
      user= User.find(@missing_post.user_id)
      AdminMailer.contact_by_email(user, @missing_post, modified_name, modified_lastname, modified_phone, modified_mail, dogname, omd_notifications_mail, dni).deliver_later

      mensaje= 'Solicitud de contacto exitosa, espere la respuesta!'
      redirect_to missing_posts_path, notice: mensaje
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_missing_post
      @missing_post = MissingPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def missing_post_params
      params.require(:missing_post).permit(:name, :breed, :size, :gender, :description, :zone, :user_id, :finished, :confirmed_at, :age, :image)
    end

    def require_owner_or_admin
      @missing_post = MissingPost.find(params[:id])
      # Verifica si el usuario es el propietario del recurso o es un administrador
      unless current_user && (current_user.id == @missing_post.user_id || current_user.admin?)
        redirect_to dashboard_home_path
      end
    end

end

app/helpers/missing_posts_helper.rb
module MissingPostsHelper
end

app/views/missing_posts/_form.html.erb
<div class="container">
  <div class="d-flex justify-content-center align-items-center mt-1">
    <div class="col-md-7 col-lg-8">
      <h4 class="mb-3">Datos del perro</h4>
      <%= form_with(model: missing_post) do |f| %>
        <div class="row g-3">
          <div class="col-sm-6">
              <%= f.label :Nombre, class:"form-label" %>
              <%= f.text_field :name, autofocus: true, autocomplete: "name", class:"form-control", placeholder: "", required: "required"%>
          </div>

          <div class="col-sm-6">
              <%= f.label :Raza, class:"form-label" %>
              <%= f.text_field :breed, autofocus: true, autocomplete: "breed", class:"form-control", placeholder:"", required: "required"%>
          </div>
            
          <div class="col-4">
              <%= f.label :Tamaño, class:"form-label" %>
              <%= f.select :size, ['Muy chico','Chico','Mediano','Grande','Muy grande'], { prompt: 'Selecciona el tamaño'}, { class: 'form-select', required: 'required', placeholder:""} %>
          </div>
          
          <div class="col-4">
            <%= f.label :Sexo, class: "form-label" %>
            <%= f.select :gender, ['Hembra', 'Macho'], { prompt: 'Selecciona el sexo' }, { class: 'form-select', required: 'required', placeholder:""} %>
          </div>

          <div class="col-4">
            <%= f.label :Edad, class: "form-label" %>
            <%= f.number_field :age, min:0, class:"form-control", required: 'required', placeholder: "Solo años" %>
          </div>

          <div class="col-12">
            <%= f.label :'Zona en la que se perdió', class:"form-label" %>
            <%= f.text_area :zone, autofocus: true, autocomplete: "zone", class:"form-control", placeholder:"", required: "required"  %>
          </div>

          <div class="col-12">
            <%= f.label :'Otros datos para facilitar la busqueda', class:"form-label" %>
            <%= f.text_area :description, autofocus: true, autocomplete: "description", class:"form-control", placeholder: "", required: "required"%>
          </div>

          <div class="field">
            <%= f.label :Foto %>
            <%= f.file_field :image, accept: 'image/*' %>
          </div>

        </div>

        <% if flash[:alert] %>
          <div class="alert alert-danger my-2 p-1 text-center">
            <%= flash[:alert] %>
          </div>
        <% end %>   

        <% if missing_post.errors.any? %>
          <div class="alert alert-danger my-2 p-1 text-center">
            <ul>
              <% missing_post.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <hr class="mt-4">
        <%= f.submit "Publicar perro perdido", class:"w-100 btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/missing_posts/_missing_post.html.erb
<div class="card-body">
  <h2 class="card-title mb-2"><%= missing_post.name %></h2>
  <div class="mb-2">
  <p> </p>
  </div>
  <% if missing_post.image.attached? %>
    <%= image_tag(missing_post.image, size: '400x400') %>
  <% end %>  
  <% if missing_post.finished? %>
    <p class="card-text fs-5">¡ENCONTRADO!</p>
    <p class="card-text"><strong>Fecha de publicación: </strong><%= missing_post.created_at.strftime("%d/%m/%Y | %H:%M") %></p>
    <p class="card-text"><strong>Encontrado/a el dia </strong><%= missing_post.confirmed_at.strftime("%d/%m/%Y | %H:%M") %></p>
  <% else %>
    <p class="card-text fs-5"><%= missing_post.breed %></p>
    <p> </p>
    <div class="row">
        <div class="col">
            <p class="card-text"><strong>Sexo: </strong><%= missing_post.gender %></p>
        </div>
        <div class="col">
            <p class="card-text"><strong>Edad: </strong><%= missing_post.age %></p>
        </div>
        <div class="col">
            <p class="card-text"><strong>Tamaño: </strong><%= missing_post.size %></p>
        </div>
        <p> </p>
    </div>
    <p class="card-text"><strong>Se perdió por: </strong><%= missing_post.zone %> </p> 
    <p class="card-text"><strong>Información extra: </strong><%= missing_post.description %> </p>
    <p class="card-text"><strong>Fecha de publicación: </strong><%= missing_post.created_at.strftime("%d/%m/%Y | %H:%M") %></p>
  <% end %>
</div>

app/views/missing_posts/confirm_delete.html.erb
<div class="container-fluid mt-4 px-2">
  <div class="modal modal-sheet position-static d-block p-4 py-md-2" tabindex="-1" role="dialog" id="modalSheet">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-4 shadow">
        <div class="modal-header border-bottom-0">
          <h2 class="modal-title fs-5 ">Confirmar eliminación</h2>
        </div>
        <div class="modal-body py-0">
            <p>¿Estás seguro de que deseas eliminar esta publicación?</p>
        </div>
        <div class="modal-footer flex-column align-items-stretch w-100 pb-3 border-top-0">
          <%= button_to "Confirmar", @missing_post, method: :delete, class:'btn btn-danger w-100' %>
          <%= link_to "Volver atras", missing_post_path, class:"btn btn-outline-secondary" %>
        </div>     
      </div>
    </div>
  </div>
</div>

app/views/missing_posts/edit.html.erb
<div class="container-fluid mt-4 px-2">
  <h2>Editar publicación</h2>
  <hr>
  <%= render "form", missing_post: @missing_post %>

  <div class=""> 
    <div class="container">
      <div class="d-flex justify-content-center align-items-center mt-2">
        <div class="col-md-7 col-lg-8">
          <%= link_to "Volver atras", @missing_post, class: "btn btn-outline-secondary w-100 mt-0 mb-4"%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/missing_posts/index.html.erb
<div class="container-fluid mt-4 px-2">
  <h2>Perros perdidos</h2>
  <hr>
  <% if user_signed_in? == false %>
    <%= link_to "Volver atras", root_path, class:"btn btn-outline-secondary px-3 mb-2"%>
  <% end %>
  <% if user_signed_in? %>
    <%= link_to "Publicar perro perdido", new_missing_post_path, class:"btn btn-primary px-3 mb-2"%>
  <% end %>
  <% if flash[:alert].present? %>
    <div class="alert alert-danger">  
      <%= flash[:alert] %>
    </div>
  <% elsif flash[:notice].present? %>
    <div class="alert alert-success">  
      <%= flash[:notice] %>
    </div>
  <% end %>
  
<div class="my-3" id="appointments">
    <div class="row">
      <% if @missing_posts.present? %>
        <% @missing_posts.each do |missing_post| %>
          <div class="col-lg-4 col-md-6 col-sm-12 mb-3">
              <div class="card">
                  <div class="card-body text-center">
                      <h5 class="card-title display-6 font-weight-bold p-1"><%= missing_post.name %></h5>
                      <% if missing_post.image.attached? %>
                        <%= image_tag(missing_post.image, size: '200x200') %>
                      <% end %>
                      <% if missing_post.finished? %>
                        <p class="card-text fs-5">¡ENCONTRADO!</p>
                        <p class="card-text"><strong>Se habia perdido por: </strong><%= missing_post.zone %> </p>
                      <% else %>
                        <p class="card-text fs-5"><%= missing_post.breed %></p>
                        <div class="row">
                            <div class="col">
                                <p class="card-text"><strong>Sexo: </strong><%= missing_post.gender %></p>
                            </div>
                            <div class="col">
                                <p class="card-text"><strong>Edad: </strong><%= missing_post.age %></p>
                            </div>
                            <div class="col">
                                <p class="card-text"><strong>Tamaño: </strong><%= missing_post.size %></p>
                            </div>
                        </div>
                        <p> </p>
                        <p class="card-text"><strong>Se perdió por: </strong><%= missing_post.zone %> </p>
                        <p class="card-text"><strong>Información extra: </strong><%= missing_post.description %> </p>
                      <% end %>
                  </div>

                  <div class="card-body">
                      <button class="btn btn-secondary" type="button" data-bs-toggle="modal" data-bs-target="#show_request">
                          <%= link_to "VER MAS  ", missing_post, class:"text-white text-decoration-none pe-2"%>
                          <i class="bi bi-plus-circle align-items-center mx-1"></i>
                      </button>
                  </div>
              </div>
          </div>
        <% end %>
      <% else %>
        <div class="col-12">
          <p>No hay perros perdidos subidos a la aplicación en este momento.</p>
        </div>
      <% end %>
    </div>
</div>   

app/views/missing_posts/new.html.erb
<div class="container-fluid mt-4 px-2">
  <h2>Agregar publicación</h2>
  <hr>
  <%= render "form", missing_post: @missing_post %>

  <div class=""> 
    <div class="container">
      <div class="d-flex justify-content-center align-items-center mt-2">
        <div class="col-md-7 col-lg-8">
          <%= link_to "Volver atras", missing_posts_path, class: "btn btn-outline-secondary w-100 mb-4"%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/missing_posts/show.html.erb
<div class="modal modal-sheet position-static d-block p-0 py-md-0 my-0" tabindex="-1" role="dialog" id="modalTour">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-4 shadow">
      <div class="modal-body p-4">
        <div class="text-center my-3">
          <%= render @missing_post %>
        </div>
        <div class="row g-3 text-center pb-2">
          <% if  current_user && (current_user.id == @missing_post.user_id || current_user.role == 'admin')%>
            <% if !@missing_post.finished %>
              <div class="col-6">
              <%= form_with(model: @missing_post, url: confirm_missing_post_path(@missing_post), method: :patch) do |form| %>
                <%= form.hidden_field :finished, value: true %>
                <%= form.hidden_field :confirmed_at, value: Time.current %>
                <%= form.submit "Apareció", class: "btn btn-success w-100" %> 
              <% end %>
              </div>
              <div class="col-6">
                <%= link_to "Editar", edit_missing_post_path(@missing_post), class: "btn btn-primary w-100"%>
              </div>  
              <div class="col-6">
                <%= link_to "Eliminar", confirm_delete_missing_post_path(@missing_post), class: "btn btn-danger w-100" %>
              </div>
            <% end %>
          <% else %>
            <div class="col-6">
            <% if !@missing_post.finished %> 
              <%= link_to "Contactar", mp_solicitar_path(@missing_post), class: "btn btn-primary w-100"%>
            <% end %>
            </div>  
          <% end %>
          <% if @missing_post.finished %>
            <div>
              <% if current_user.role == 'admin' %>
                <%= link_to "Eliminar", confirm_delete_missing_post_path(@missing_post), class: "btn btn-danger w-100" %> 
              <% end %>
            </div>
            <div>
                <%= link_to "Volver atras", missing_posts_path, class: "btn btn-outline-secondary w-100 "%>
            </div> 
          <% else %>  
            <div class="col-6">
                <%= link_to "Volver atras", missing_posts_path, class: "btn btn-outline-secondary w-100 "%>
            </div> 
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/missing_posts/solicitar.html.erb
<div class="container-fluid mt-4 px-2">
  <h2>Solicitud de contacto</h2>
  <hr>
  <p><strong>Datos de contacto</strong></p>
  <%= form_with(method: :post) do |f|  %>
    <div class="row g-3">
      <div class="col-sm-6">
        <%= f.label :Nombre, class:"form-label" %>

        <%= f.text_field :name, autofocus: true, autocomplete: "name", class:"form-control", placeholder:"", value:@name, required: "required"%>
      </div>

      <div class="col-sm-6">
        <%= f.label :Apellido, class:"form-label" %>
        <%= f.text_field :lastname, autofocus: true, autocomplete: "lastname", class:"form-control", placeholder:"", value:@lastname, required: "required"%>
      </div>
              
      <div class="col-12">
        <%= f.label :'Correo electronico', class:"form-label" %>
        <%= f.email_field :mail, autofocus: true, autocomplete: "mail", class:"form-control", placeholder:"", value:@mail, required: "required"%>
      </div>
            
      <div class="col-12">
        <%= f.label :Telefono, class:"form-label" %>
        <%= f.telephone_field :phone, autofocus: true, autocomplete: "phone", class:"form-control", placeholder:"", value:@phone, required: "required"%>
      </div>
    </div>

    <% if flash[:alert] %>
      <div class="alert alert-danger my-2 p-1 text-center">
        <%= flash[:alert] %>
      </div>
    <% end %>   

    <hr class="my-4">
    <%= f.submit "Contactar", class:"w-100 btn btn-primary btn-lg" %>
  <% end %>

  <div class="my-2">
    <%= link_to "Volver atras", missing_posts_path, class:"w-100 btn btn-outline-secondary btn-lg"%>
  </div>
</div>